2020-01-23 18,33,35.914207,       Test
2020-02-03 10:47:55.884718:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05525110>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:47:57.122407:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x055500D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:47:58.362124:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x055510D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:47:59.600776:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05551070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:00.839489:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x055510F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:02.078263:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x055510B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:22.268220:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CC3D50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:23.481972:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDA070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:24.698717:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDA070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:25.917456:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDA070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:27.136196:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDA070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:28.353938:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDA070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-02-03 10:48:29.573674:       HTTPSConnectionPool(host='rwdevon.clubspeedtiming.com', port=443): Max retries exceeded with url: /SP_Center/signalr (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03CDA070>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
